### ISSUE TITLE
Don't reorder attributes

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/translate-codelists#1]
I am not sure if this is really possible without a lot of work. I think it is probably happening around this line:

https://github.com/codeforIATI/translate-codelists/blob/master/translate.py#L58-L60

Unfortunately this was kind of necessary to output the indentation in a way that would be consistent with the existing file.

**Comment by andylolz** [comment]
Yeah so it sounds like minidom stores attributes as an unordered dictionary, so it seems like it’s not possible to go via minidom and maintain attribute order.

Another option might be to use [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)’s `prettify`, with a custom formatter. I don’t know if that is getting a bit too hacky, though.
